services:
  registry-mirror:
    image: registry:3.0
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./registry/mirror/data:/var/lib/registry
      - ./registry/mirror/config/config.yml:/etc/distribution/config.yml
      - ./registry/mirror/config/htpasswd:/etc/docker/registry/htpasswd
    environment:
      - OTEL_TRACES_EXPORTER=none
  registry-writeable:
    image: registry:3.0
    restart: unless-stopped
    ports:
      - 5001:5000
    volumes:
      - ./registry/writeable/data:/var/lib/registry
      - ./registry/writeable/config/config.yml:/etc/distribution/config.yml
      - ./registry/writeable/config/htpasswd:/etc/docker/registry/htpasswd
    environment:
      - OTEL_TRACES_EXPORTER=none