version: 0.1
log:
  fields:
    service: registry-mirror
storage:
  delete:
    enabled: true
  filesystem:
    rootdirectory: /var/lib/registry
proxy:
  remoteurl: https://registry-1.docker.io
http:
  addr: :5000
auth:
  htpasswd:
    realm: Registry Realm
    path: /etc/docker/registry/htpasswd